name: Bug Report
description: File a bug report
title: "Bug: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report !
        
        Please use [Chantal search engine](https://chantal.aurelienpierre.com) to find out if another user has already faced, reported (and perhaps solved) your issue. 
        Avoiding duplicates spares everybody's time. 

        __What is a bug ?__

        - the software crashes,
        - the software hangs indefinitely,
        - the software exports an image that doesn't look like the preview,
        - the software displays obviously inconsistent previews (ghosts, black blotches, full-black or full-white),
        - the software has become noticeably slower to process a specific module on a specific image than in the past (regression).

        __What is not a bug ?__

        - the software produces images that don't look like out-of-camera JPEG files,
        - the software doesn't magically fix images that were damaged to begin with (clipped highlights, high-ISO noise),
        - the software is slow to process some specific module on some specific hardware, with no proof that is has ever been faster,
        - insane module settings produce insane image results.
        
        Ansel has a codebase of more than 300k lines. Chasing bugs in here requires proper methodology: minimal reproducing examples.

        - if you are using custom ICC color profiles on your desktop, disable them or reset them to sRGB (default), and see if that fixes your issue.
        - if you are using OpenCL, disable it, and see if that fixes your issue.
        - if you are facing image/preview issues, disable all modules, then enable only one at a time, until you find the culprit. If you don't, re-enable them all, one by one, in pipeline order, until you find the culprit. Report here which one it was. 
        _Modules that come late in the pipeline inherit earlier module's problems. Because a problem is made obvious/magnified at some late step doesn't mean it was created there._

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please read [A culture of problem solving in open-source projects](https://community.ansel.photos/view-discussion/a-culture-of-problem-solving-in).
      options:
        - label: I have read this document and I accept the conditions
          required: true
  - type: checkboxes
    id: search
    attributes:
      label: Search previous report
      description: Please search your symptoms with [Chantal search engine](https://chantal.aurelienpierre.com) to see if a previous report already exists.
      options:
        - label: I have searched my issue
          required: true  
  - type: markdown
    attributes:
      value: ---
          
  - type: dropdown
    id: os
    attributes:
      label: Computer's operating system
      description: What OS are you using ?
      options:
        - Windows 7, 8, 10, or 11
        - Linux
        - MacOS Intel x86
        - MacOS ARM64
      default: 1
  - type: dropdown
    id: gpu
    attributes:
      label: What GPU do you have ?
      description: If more than one GPU (embedded/discrete), report the brand of the discrete GPU.
        - No GPU
        - I don't know
        - Nvidia
        - AMD/ATI
        - Intel
        - Other
      default: 1
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Ansel version
      description: You can find the version number or commit hash in the name of the [pre-built binary](https://github.com/aurelienpierreeng/ansel/releases/tag/v0.0.0), in the app global menu "Help" -> "About", or with `git rev-parse --short HEAD`
    validations:
      required: true
  - type: dropdown
    id: binary
    attributes:
      label: Type of binary
      description: What kind of Ansel executable do you run ? Problems with packages from distributions's repositories need to be reported to package maintainers.
      options:
        - Self-compiled (GCC or Clang)
        - Pre-built packages provided by the Ansel project (.AppImage, .EXE)
        - Linux packages from distributions or third-party packagers (Suse, Fedora, etc.)
      default: 1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen ?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    attributes:
      value: If you need to upload images and XMP files, please zip them together under a meaningful name and drop them above or on [Aurélien Pierre's private cloud](https://cloud.apmlt.net/s/YAdfYajPkE5nLyW). Files uploaded to AP's private cloud remain strictly confidential.
  - type: dropdown
    id: with-opencl
    attributes:
      label: Does your problem occur with OpenCL enabled ?
      description: OpenCL use relies on a graphic card (GPU), proper GPU OpenCL drivers installed, and the software preference enabled.
      options:
        - "Yes"
        - "No"
        - I don't know
      default: 1
    validations:
      required: true
  - type: dropdown
    id: without-opencl
    attributes:
      label: Does your problem occur with OpenCL disabled ?
      description: OpenCL disabled means the software runs on CPU only. Ansel has an option in global menu "Edit" -> "Preferences" -> "Performance" to disable OpenCL. If you don't have a GPU, OpenCL is disabled by default.
      options:
        - "Yes"
        - "No"
        - I don't know
      default: 1
    validations:
      required: true
  - type: input
    id: bisect
    attributes:
      label: Previous Ansel version that use to work
      description: If you did not face this issue with a previous Ansel issue, report here the last-known working version number. You can try [older packages](https://github.com/aurelienpierreeng/ansel/releases/tag/v0.0.0) or use `git bisect`.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Output of `ansel -d all`
      description: Please copy and paste the output of Ansel started in command line if you can. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: backtrace
    attributes:
      label: Backtrace
      description: In case of a crash, please copy and paste the content of the backtrace file, usually stored in `/tmp/ansel_backtrace_xxxx_txt`. If no backtrace is produced, you can try to launch Ansel with `gdb ansel`, then type `run`. When it crashes, type `bt full` and copy-paste the output here. This will be automatically formatted into code, so no need for backticks.
      render: shell
