name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report !
        
        Please use [Chantal search engine](https://chantal.aurelienpierre.com) to find out if another user has already faced, reported (and perhaps solved) your issue. 
        Avoiding duplicates spares everybody's time. 

        __What is a bug ?__

        - the software crashes,
        - the software hangs indefinitely,
        - the software exports an image that doesn't look like the preview,
        - the software displays previews containing black blotches, or are fully black or white,
        - the software has become noticeably slower to process a specific module on a specific image than in the past (regression).

        __What is not a bug ?__

        - the software produces images that don't look like out-of-camera JPEG files,
        - the software doesn't magically fix images that were damaged to begin with (clipped highlights, high-ISO noise),
        - the software is slow to process some specific module on some specific hardware, with no proof that is has ever been faster.
        
        Ansel has a codebase of more than 300k lines. Chasing bugs in here requires proper methodology: minimal reproducing examples.

        - if you are using custom ICC color profiles on your desktop, disable them or reset them to sRGB (default).
        - if you are using OpenCL, disable it.
        - if you are facing image/preview issues, disable all modules, then enable only one at a time, until you find the culprit. If you don't, re-enable them all, 
        one by one, in pipeline order, until you find the culprit. Report here which one it was. _Modules that come late in the pipeline inherit earlier module's problems.
        Because a problem is made obvious/magnified at some late step doesn't mean it was created there._

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please read [A culture of problem solving in open-source projects](https://community.ansel.photos/view-discussion/a-culture-of-problem-solving-in).
      options:
        - label: I have read this document
          required: true
  - type: checkboxes
    id: search
    attributes:
      label: Search previous report
      description: Please search your symptoms with [Chantal search engine](https://chantal.aurelienpierre.com) to see if a previous report already exists.
      options:
        - label: I have searched my issue
          required: true  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
