blank_issues_enabled: false
contact_links:
  - name: Ansel Community Support
    url: https://community.ansel.photos/discussions-home
    about: Please ask and answer questions here.
  - name: Feature requests
    url: https://community.ansel.photos/discussions-category?category=6
    about: Ansel does not accept feature requests. To talk about your workflow problems, open a discussion on the community forum.
