name: Matrix bot

on:
  push:
    branches:
      - master

jobs:
  matrix_action_job:
    runs-on: ubuntu-latest
    name: Send Message to Matrix Room
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: matrix-commit
      uses: krazykirby99999/matrix-commit@v1

      with:
        homeserver: ${{ secrets.MATRIX_SERVER }}
        username: "Chantal AI"
        access_token: ${{ secrets.MATRIX_ACCESS }}
        room_id: "!khBjOtEnQNuCYlWScJ:matrix.org"
        message: "#### New commit : "
